### ISSUE TITLE
campaign 

### ISSUE THREAD

**Issue by plamagd** [Infiland/AsteroidsFeedback#1]
whenever i try to go to campaign i press continue and i click my ship i get an error,
is this supposed to happen?

**Comment by Infiland** [comment]
Can you tell me what is the exact error? Does the game crash and if so, can you send me the error message?

**Comment by plamagd** [comment]
It happened when i first opened the game, i clicked continue instead of campaign

**Comment by plamagd** [comment]
Might have been my fault lol

**Comment by Infiland** [comment]
Good that you report stuff here because when I test I usually run the save file that I have. I might need to prevent the issue by doing a couple of playthroughs with different saves. I'll see if I can replicate this bug, thank you

**Comment by Infiland** [comment]
Issue now fixed in Release 1.0.0a
