### ISSUE TITLE
Purple Credit bug - infinite credits

### ISSUE THREAD

**Issue by DiQfitZwell** [Infiland/AsteroidsFeedback#13]
After completely the weekly planet I went to resume my campaign by clicking start and then continue. It rather than resumes my campaign takes me back the weekly planet battle where I have the 4 sectors already complete and I can just turn in gold for credits and repeat endlessly.

**Comment by Infiland** [comment]
I will test this and fix this ASAP, thank you for the bug report

**Comment by Infiland** [comment]
Fixed in 1.0.7
