### ISSUE TITLE
Game crash after starting the earth boss mission

### ISSUE THREAD

**Issue by DiQfitZwell** [Infiland/AsteroidsFeedback#14]
Happens within 10 seconds or less of starting the level. I've swapped abilities and such to test if it was from a particular one, happens everytime so far.
___________________________________________
############################################################################################
ERROR in
action number 1
of  Step Evento_finalboss
for object o_playerdamage:

Variable Get 100112 (101343, -2147483648)############################################################################################
gml_Script_bulletdestroy@gml_Object_o_playerdamage_Collision_o_allmeteroids (line 33)
gml_Object_o_playerdamage_Collision_o_allmeteroids (line 53)

**Comment by Infiland** [comment]
Seems like there's an issue with the final boss not taking damage properly. I'll fix this ASAP

**Comment by Infiland** [comment]
Fixed in 1.0.7a
