### ISSUE TITLE
release 1.0.7a bugs

### ISSUE THREAD

**Issue by bobinsky01** [Infiland/AsteroidsFeedback#15]
hey dudes wassup with yall! so everytime I log on to the game, I am locked on 24 levels and is because it says that im a cheater, even though i did literally nothing to cheat. I also cannot advance to the next planets and the sections that i completed arent marked as completed like it is meant to. hope everything made sense
![image](https://github.com/Infiland/AsteroidsFeedback/assets/90533811/df868a3b-ad02-4737-9031-4d65ad943b3e) [image shows message that i am a cheater (shows every time i log on)
![image](https://github.com/Infiland/AsteroidsFeedback/assets/90533811/38caa431-184c-4ff8-9830-af2840f6c600) [ik this image doesnt show much but i literally beat the planet like 4 times and it shows that i havent advanced yet]

**Comment by Infiland** [comment]
You were flagged for cheating for whatever reason, when that happens the game locks you out from progressing and sending leaderboards, the only way to turn it off is to delete the entire %appdata% folder of Asteroids (or reverse engineer the change but that is almost impossible)

Is it possible that you were tinkering with save files?
