### ISSUE TITLE
Game crash on final boss 

### ISSUE THREAD

**Issue by DiQfitZwell** [Infiland/AsteroidsFeedback#16]
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object o_meteroidspawner:

Attempting to set Instance id 127606 with Object Index 79 (o_money) with invalid bound top -inf bottom -inf left inf right inf
############################################################################################

**Comment by Infiland** [comment]
Could you tell me at what point this crash happened? I know it happened at the boss but did it happen when trying to kill the boss or at some other time?

**Comment by DiQfitZwell** [comment]
___________________________________________
############################################################################################
ERROR in action number 1
of Create Event for object o_meteroidspawner:
Attempting to set Instance id 129191 with Object Index 79 (o_money) with invalid bound top inf bottom inf left inf right inf
############################################################################################
Boss had 2 health bars left. If it matters for weapons Ive been using laser shotgun and bouncy balls.

**Comment by DiQfitZwell** [comment]
Happened when starting wave 6 boss had 2 health bars left.
___________________________________________
############################################################################################
ERROR in action number 1
of Create Event for object o_meteroidspawner:
Attempting to set Instance id 124400 with Object Index 79 (o_money) with invalid bound top -inf bottom -inf left inf right inf
############################################################################################
Edit recorded the boss fight if that helps - https://www.youtube.com/watch?v=R2A3nPb7xnE 
@3:07 error code occurs.

**Comment by Infiland** [comment]
Thanks for the video! I'll try to replicate it myself now and see to fix it

**Comment by Infiland** [comment]
Okay, try to see if the bug happens now in 1.1.1a, I've updated the game now and probably fixed instances there a number could be divided by 0, causing "inf bound" issues. I apologize for this mess :pray:

**Comment by Infiland** [comment]
Seems no further comments were made so I assume this has been fixed
