### ISSUE TITLE
Clone Bug?

### ISSUE THREAD

**Issue by Saccadence** [Infiland/AsteroidsFeedback#19]
I'm not sure how to provide evidence of this, as it is more based on feel than objective nature. It seems that unequipping the clone "weapon" causes the lower-level stats from it to carry over to a non-clone round.

In other words, after I unequip the clone, the next sector I start up feels like I don't have the same level of utilities and weapons that I have without the clone. I believe this requires a restart to fix and/or leaving the campaign (where this was mostly occurring since that's the only mode I've played much of).

**Comment by Infiland** [comment]
I'll test it out and see if I get the same issue. It could be an oversight so I'll look into it

**Comment by Infiland** [comment]
It seems that the bug was caused by going to the pause screen and clicking settings. I've fixed this in 1.1.5, but let me know if anything weird happens
