### ISSUE TITLE
Modified game files warning.

### ISSUE THREAD

**Issue by Davisa94** [Infiland/AsteroidsFeedback#20]
When attempting to launch the game the first time it would not launch. I switched to using GE-Proton to run it and it needed to download an update. After downloading and launching the game, a message appeared saying that I had played the game before and that I had modified the game files. Another important note is that the game was initially downloaded via steam transfer over the local network. May have been caused by the host of the transfer being a windows machine and mine being linux, not sure if there is a native linux version or not though.

**Comment by Infiland** [comment]
While I have technically added "native support" for linux, the linux version is barely tested. The "game files" warning only appears at the very start of the game if there exists a file or folders in the %appdata% directory, however there is a possibility that a anticheat could be activated, but I assume you are just talking about files being changed and that's it. Not sure how it found that out, my guess is steam could've created the "steam_autocloud.vdf" file, which could activate it

Proton is also not tested, I've had some people try it out but with mixed results. I probably need to go look through it more or get someone to help me with this.

**Comment by Infiland** [comment]
Fixed the issue with the game not launching properly in version 1.1.7, im going to close this issue assuming it has been fixed
