### ISSUE TITLE
[Linux] Does not work when using a separate drive for games

### ISSUE THREAD

**Issue by stevietrouble** [Infiland/AsteroidsFeedback#21]
The linux version has the directory hardcoded in `ast.sh`:

```bash
#!/bin/bash
export LD_LIBRARY_PATH="./assets/:$LD_LIBRARY_PATH:/usr/lib"
"/home/$USER/.steam/steam/steamapps/common/Asteroids ++/Asteroids___"
```

This should be instead something like:

```bash
#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export LD_LIBRARY_PATH="./assets/:$LD_LIBRARY_PATH:/usr/lib"
"${SCRIPT_DIR}/../Asteroids___"
```

Also many of the assets won't load for me and show placeholder tiles, possibly for the same reason (hardcoded directory).

Hope this helps.

**Comment by Infiland** [comment]
I'll change the ast.sh file to this and test out tomorrow. And yeah the "placeholder" sprites is a bug specifically on linux.

I'll try to get it done in 1.1.7

**Comment by Infiland** [comment]
Alright, changed in 1.1.7, see how it works now for you :)

**Comment by stevietrouble** [comment]
That worked, thank you!
