### ISSUE TITLE
Golden Shower bug?

### ISSUE THREAD

**Issue by amorata604** [Infiland/AsteroidsFeedback#23]
I don`t know if this is the reason for getting this achievement. I only know, as a final round, lot`s of golden asteroids came and I've completed the round without dying. Could be this a bug? I don`t have the Steam achievement.

![image](https://github.com/user-attachments/assets/7b57c5ff-6008-43dd-8c5c-c1b1386c2f02)

**Comment by Infiland** [comment]
The golden shower achievement should activate if the "golden shower wave" appeared. Now this achievement would only appear if the steam API was active (which should be at the start of the game). I'll try to see if there's an actual activation issue with it

**Comment by Infiland** [comment]
Fixed in 1.1.7d
