### ISSUE TITLE
Light blue asteroids

### ISSUE THREAD

**Issue by amorata604** [Infiland/AsteroidsFeedback#25]
In comparison to the normal ones, do these have more protection against bullets?

**Comment by Infiland** [comment]
Yes, light blue asteroids are more resistant and have more health.

Each asteroid type has its "strength" and "weakness" for each player weapon
So for instance, yellow asteroids are much stronger against the sniper, so the sniper deals less damage to yellow asteroids, but weaker against a machine gun.
