### ISSUE TITLE
Game crashes when selecting the "Campaign" option on the start menu.

### ISSUE THREAD

**Issue by Rel4tive** [Infiland/AsteroidsFeedback#29]
Just as the title says. Here's the code error:

___________________________________________
############################################################################################
ERROR in action number 1
of Draw Event for object o_mainmenu:
STRING argument is unset############################################################################################
gml_Object_o_mainmenu_Draw_64 (line 221)

**Comment by Infiland** [comment]
Can you test again and see if it crashes? I think I fixed it just now

**Comment by Rel4tive** [comment]
Yap, it works now!
