### ISSUE TITLE
Weapon reset level bug

### ISSUE THREAD

**Issue by CqtnuNick** [Infiland/AsteroidsFeedback#3]
that one bug:
_I copied these out of my notes because it's the same bug._

1. "going to main menu unselected my campaign weapons and ability, and equipped Rocket Launcher as my first gun (i had it unequipped previously). (VERSION: 1.0.0a)"

2. "When moving on to Jupiter, my weapons and ability were unequipped and my Machine Gun was equipped. it was also reset to level 1, which previously was 4-6. it's xp wasn't reset. (VERSION: 1.0.0a)"

3. "When moving to Saturn, ability and weapons got unequipped, first slot has new weapon (Bombs) and it's level got reset to 1 even though it was upgraded. it'x xp wasn't reset. (VERSION: 1.0.1)"

4. "When moving to Neptune, ability and weapons got unequipped, first slot has new weapon (Shotgun) and it's level got reset to 1 even though it was upgraded. it's xp wasnt reset. (VERSION: 1.0.1a)"

I don't remember when, but somewhen at the start (not sure if before 1. or after) (1.0.0a) this happened with the Rifle.

The bug seems to be picking the weapons in order but i've written down that the rocket launcher was reset before the machine gun was. dont know why.

**Comment by Infiland** [comment]
Everytime you move to a new planet, the game unequips all weapons and abiliities, removes some weapons and grants a random weapon (random but based on seed). However unequpping doesn't make sense and probably sparks confusion so I'll get rid of that in the game. Thanks :)

**Comment by CqtnuNick** [comment]
yeah but also it resets the weapon's level to level 1 even if you have it upgraded

**Comment by Infiland** [comment]
Also took care of that issue, found that out when fixing it :) Now it will upgrade by 1 level instead of setting it

**Comment by CqtnuNick** [comment]
what if you dont have enough xp for the next level? or if you have lvl 12?

**Comment by Infiland** [comment]
Level 12 weapons wont be leveled to level 13, and exp requirement wont count :)

**Comment by Infiland** [comment]
Fixed in 1.0.2b
