### ISSUE TITLE
Time stop Jupiter Boss

### ISSUE THREAD

**Issue by BrawnyVolt** [Infiland/AsteroidsFeedback#30]
Jupiter boss can activate abilities (ex: ball and reflect) while under time stop. It both continues (if it started to ability before time stop was activated) and begins (it turned on reflect while I had over a second left on time stop, killing me with my own bullets almost instantly) abilities most likely to their full duration.

**Comment by Infiland** [comment]
Will be fixed in 1.1.8, thanks!

**Comment by Infiland** [comment]
Fixed in 1.2.0
