### ISSUE TITLE
Realistic campaign achievement doesn't appear to be popping

### ISSUE THREAD

**Issue by kyle2662** [Infiland/AsteroidsFeedback#35]
Have completed the Pluto campaign on realistic twice - the second time with no continues and the achievement didn't pop? Perhaps I'm missing a criteria I'm unaware of?

**Comment by kyle2662** [comment]
Achievement popped later when another achievement was earned. Closing

**Comment by Infiland** [comment]
The game does give achievements but it's currently given to the player when they close the game, which is a bug. It's a problem with the extension I am using.
