### ISSUE TITLE
Using Skip Ability causes softlock if clone weapon is active

### ISSUE THREAD

**Issue by Completed24** [Infiland/AsteroidsFeedback#37]
For some weird reason, you could use the skip ability twice provided you have the Clone Weapon Active. This bug will softlock the stage, forcing the player to return to the shop.

Bug Replication:
1: Have Clone Weapon And Skip Ability Equipped
2: Enter any sector and Activate Skip Ability
3: Trigger the Clone Weapon Effect by dying
4: Activate Skip Again
5: Clear the stage
6: Game softlocks, requires leaving the stage to mitigate.

**Comment by Infiland** [comment]
Thanks for this report, I'll look into it!

**Comment by Completed24** [comment]
Extra Info:
Game Version: Steam Release 1.2.1

**Comment by Infiland** [comment]
Alright, updated the game to 1.2.2
Try it now but I think it should be fixed, going to close this issue if its confirmed

**Comment by Infiland** [comment]
Fixed in 1.2.5
