### ISSUE TITLE
Recruitments have the same name

### ISSUE THREAD

**Issue by CqtnuNick** [Infiland/AsteroidsFeedback#4]
![image](https://github.com/Infiland/AsteroidsFeedback/assets/173467755/7efd0ce2-7d96-484f-8e6b-bedd40136ab3)

**Comment by CqtnuNick** [comment]
Might have been due to the newest update, or due to this being a pluto campaign

**Comment by Infiland** [comment]
Yes its a bug, its supposed to be random but I accidentally left it like this

**Comment by Infiland** [comment]
Fixed in 1.0.2c
