### ISSUE TITLE
Saturn Achievement broken

### ISSUE THREAD

**Issue by ColdHorizon** [Infiland/AsteroidsFeedback#40]
I have beaten Saturn and i did not get the achievement

I only had one sector left and beaten it and i still got to Uranus and i have the other achievements for the other planets

I hope this helps you.

**Comment by ColdHorizon** [comment]
Actually i just needed to beat uranus and quit the game

**Comment by Infiland** [comment]
Yeah, all achievements work properly, it's just that the extension that I am using to communicate with the Steam API is for some reason delayed up to when the game closes, which is why this happens and is a bug. I'm looking to fix this, but the fix needs to be done on their end
