### ISSUE TITLE
Catnu's suggestions list | 1.0.2b

### ISSUE THREAD

**Issue by CqtnuNick** [Infiland/AsteroidsFeedback#7]
- [x] 1. Small asteroids generated by Large asteroids drop coins, which allows for coin grinding. I think its better to make it so they don't drop coins.
- [ ] 2. Explanation for the grades (D, C, B, A, S, P, WTF) in the top right corner.
- [ ] 3. Make the Skill Tree more noticeable (with a tutorial, perhaps).
- [x] 4. After saving a sector, make all uncollected coins automatically be collected, since usually you just awkwardly fly and try not to press the mouse while you collect them all. if not, then make Recruitments (the weapon) look for coins      after the sector is cleared instead of just spinning.
- [x] 5. Specify which currency the Satellite's upgrade costs (Coins or Credits).
- [x] 6. Change/Lower the Bombs weapon's spawn sound.
- [x] 7. Make coins on the edge of the screen (partly outside of it) move a little further form the edge because they are hard to notice (This is is solved with a high enough Magnet utility but, still)
- [ ] 8. Whenever we encounter a new enemy (Asteroid color/shape, UFO...,) explain to us it's properties. Also, create a new 'Library' menu that is accessed from the Main Menu/Shop which contains every enemy we've encountered and details about    it.
- [ ] 9. When the Ability slot is empty in the Shop and we press 'Change Ability', transfer us to the 'Abilities' tab so we can choose. Same with the 'Change Weapon' button.
- [x] 10. Add your Coin Balance underneath the Satellite's 'Upgrade' button in the Battle Map, so you know if you can upgrade it or not.
- [ ] 11 .Whenever we press ESC and press 'Shop', or 'Return to Main Menu' or 'Quit to Desktop' give us a pop up warning saying our progress in this sector will be lost, and ask us to confirm.
- [ ] 12. When entering a new menu for the first time (Shop, Battle Map, etc) force us to click the question mark so we don't miss it.
- [ ] 13. Make a map of the solar system so we can see the ones we've cleared and the ones we still have left. When clicking on cleared planets, open up the Battle Map and allow us to replay the sectors. Add a boss icon to the last sector we       did/hardest sector and allow us to replay the boss, if there is one.
- [x] 14. Mention the Bouncy Ball's rage state in it's weapon description.
- [ ] 15. Add a symbol next to Weapons/Abilities/Utilities/Satellite for which you have enough coins to upgrade.
- [x] 16. Max Satellite level should let you know there is a boss in the last sector when it's the only one you have left (I assume there's only a boss when it's the last one)
- [x] 17. Specify the duration of Quad Damage in it's weapon description.
- [x] 18. Specify Quad Damage's time bonus per hit in it's weapon description.
- [x] 19. Instead of displaying MAX as a Weapon's/Utility's/Ability's level, display the level itself. You will see know it's maxed by the circle being complete, and you could see your level.
- [ ] 20. Add to the Battle Map's tutorial a description about how Idle-Conquering works.
- [x] 21. Make the Ability's icon more opaque when it's ready for easier noticeability. Alternatively, you could add an animation instead.
- [ ] 22. Add a 'Restart Sector' button for the ESC menu during a sector.
- [ ] 23. When in menus, make pressing ESC bring us backwards (from Shop to Main Menu, from Battle Map to Shop, etc).
- [x] 24. Make Satellite upgrades exponentially more expensive. In later planets you get much more money so it should be more expensive.
- [x] 25. Add an animation/sound for idle-conquering action. Whenever you do it it just turns the sector green and that's underwhelming.
- [x] 26. UFOs don't drop coins, I think they should.
- [ ] 27. Add a Critical Hit feature for higher difficulties. (Damage increase based on luck, a Utility that increases critical chance, certain guns have more critical chance than others, etc). 
- [ ] 28. Add a confirmation for hitting the Quit button in the Main Menu.
- [x] 29. Make the 'Weekly Planet Time Left' display hours instead of days when it's the last day (Currently displays 0 days left).
- [x] 30. Global stats menu seems to be bugged right now, but in-game you can only view Richest Player Leaderboard. I don't think that's intentional but if it is, make it so you can also view Highest Level Leaderboard.
- [x] 31. Make us be able to scroll up and down in the Richest Player leaderboard in-game. I was unable to earlier.
- [x] 32. Make Richest Player display lifetime credits earnt instead of current credits balance
- [x] 33. In later planets you are basically guaranteed to hit WTF grade after a wave or two, so make it more difficult to increase grades in later planets. Or don't, I'm still not sure what they are for other than some extra cash at wave skips.
- [x] 34. In the Abilities's descriptions, move the "Activate ability with X" line to a new line on every ability. Cleaner design.
- [ ] 35. Make the Nuke ability open up a GUI and let us select where to drop it on the screen. When we hover our mouse on it, display a preview of the explosion area.
- [ ] 36. Entering the Earth Boss's hitbox while he is exploding upon death kills you. I suggest making us freeze in place during that animation. It is also very loud lol.
- [ ] 37. In the Earth Boss's SECTOR SAVED Menu, where the quantity of each asteroid type you killed is displayed, you can add that the player destroyed 1x of a new asteroid type, the boss.
- [ ] 38. Instead of making the earth boss spawn children upon death, make it drop lots of Coins/Credits. Ender Dragon style. (It doesn't make a lot of sense to fight some weaker asteroids after beating a 100k hp enemy. just my opinion).
- [ ] 39. Make it so whenever you click on one of your equipped weapons, an animation plays at that weapon's shop icon so you can easily find it.
- [ ] 40. Add a confirmation pop up whenever we try to delete one of our campaigns so we don't delete it on accident.
- [ ] 41. UFO waves are generally very underwhelming compared to other waves (Novice difficulty), maybe buff them a little.
- [ ] 42. Use a different colored text for the HP in the boss's health bars (White on yellow is not very visible).
- [ ] 43. Change Recruitments's AI to not suicide into the Earth Boss. However, this might make them op since they are really strong and there's a lot of them.
- [ ] 44. In the Ship Color Customization menu, add buttons for 'Confirm Changes' and 'Cancel'.
- [ ] 45. Make Triplet asteroids leave the boss's hitbox sooner after it spawns them because they stay in it for a long time sometimes.
- [ ] 46. Give the Earth Boss an attack that you need to dodge because the gameplay is too idle. Maybe make it so it only happens when there are no enemies left, so the player will not be overwhelmed.
- [ ] 47. During the Earth Boss battle, prevent enemies from spawning from the top side of the screen.

**Comment by Infiland** [comment]
Updated your comment with checkboxes, this will be a tiny todo list :)

**Comment by crimsonnnnn** [comment]
i aint readin allat 😂
