### ISSUE TITLE
Catnu's bug reports list | 1.0.2b

### ISSUE THREAD

**Issue by CqtnuNick** [Infiland/AsteroidsFeedback#8]
(Written down during 1.0.0.a):

- [x] 1. When you try to go forward while shooting you are slowed, but if you start shooting while you are already going forward you can do both without being slowed. 

- [x] 2. The Battle Map's tutorial has a box that is a little misplaced (Refer to image) 

![BattleMapTutorialMisplacedBox](https://github.com/Infiland/AsteroidsFeedback/assets/173467755/20360add-04ab-4454-bf74-64f2485f60d6)

- [x] 3. Satellite level resets upon switching to new planet (Not sure if bug or intentional) **EDIT: THIS IS INTENTIONAL, satellite level gets reset because that satellite stays on that particular planet, but I should probably mention that in the tutorial**

- [x] 4. The Laser Gun's visual stops showing sometimes for short or prolonged periods of time, but you can hear the sound effect of it's shots. I suspect it is caused by GUI pop-ups such as "New Wave" and "Wave Skip" pop-ups. This issue seems to also happen with the Sniper's bullets and gray aiming lines. 

(Written down during 1.0.1):

- [ ] 5. UFOs always spawn from the right side of the screen.

- [x] 6. Going to the Main Menu directly from a Sector fight leaves your Recruitments in the background. 

- [x] 7. I am now realizing this would fit better in suggestions: While in the Main Menu or other menus that display your character, your character shoots automatic fire if you have a weapon with an automatic fire (Machine gun, Shotgun, Bombs, Bouncing Ball, (Pulse doesn't work for some reason)). With a Machine Gun this causes a lot of mess because the bullets stay on the screen for longer due to their ability to appear again on the other side of the screen. I think automatic fire should be removed from Main Menu.

- [ ] 8. During fighting, your Coins Balance at the top left and the REWARDED title from Super Skip ability use the font which moves them up and down, which causes them to cover each other a little.

(Written down during 1.0.1a):

- [x] 9. In the Main Menu or in other menus that display your character, your most recently active campaign's Ability Icon is displayed on the bottom left corner of your screen. You are able to use every ability in these menus. The results are as follows: 

	Dash moves you forward and lets you leave the screen if the screen is zoomed in (Ship color customization menu). 
	Timestop displays the duration above your character and does nothing else. 
	Nuke explodes at the center of the screen, dealing damage to you. If you die, the death sound is played and your character 
        disappears. 
	Super Skip does nothing. 
	Quad Damage displays the text above you and nothing else happens.
	Repair Kit does nothing.

- [x] 10. UFO rifle bullets hit asteroids and deal damage to them. (Not sure if unintentional or not) **EDIT: IT IS INTENTIONAL**

- [x] 11. When Timestop duration runs out, enemies regain their movement gradually and not instantly. (Not sure if intentional but I think it's really cool) **EDIT: IT IS INTENTIONAL**

- [x] 12. Timestop does not stop Armed asteroid's bullets and UFO's rifle bullets. Unsure about UFO rockets and machine guns.

- [ ] 13. When pressing ESC and pausing the fight with a Timestop active, the Timestop's sound keeps playing in the ESC menu.

- [x] 14. THEORY: Timestop stops enemy movement, and Pulse deals knockback to enemies. They might bug if used together. 

Maybe you should disable Pulse during Timestop since you don't get hit during it anyways. (Timestop's description says it pauses EVERYTHING except the player and it's bullets. Pulse is neither of those so it also matches the description).

- [x] 15. Rocket launcher wielding UFOs stop shooting sometimes. Requires further investigation.

(Written down during 1.0.2):

- [x] 16. Repair Kit ability does not work

- [x] 17. Dying to a Nuke which kills both you and the last enemy does not fail you and successfully clears the sector. (not really a bug). **EDIT: THIS IS INTENTIONAL, I made it so that if you somehow died but the "end screen" appears you won't lose, even if you press R to destroy yourself**

- [ ] 18. Timestop does not stop Earth Boss's spinning animation.

- [x] 19. Nuke ability does not target the Earth Boss, instead it targeted another asteroid.

- [x] 20. You can equip multiple copies of the same weapon. If you fight with them it ignores the copies.

- [x] 21. During Earth Boss, the total amount of waves is hidden so every wave is displayed as the last one. This causes the game to announce every wave as the "Final Wave". 

- [x] 22. Super skip during Earth Boss does not do anything because the game always thinks you are at the final wave.

- [x] 23. Clearing the Earth Boss's health bars does not spawn Triplet asteroids unless it is Wave 3 and onward (exact details unclear, might be different for each Triplet asteroid and health bar).

- [x] 24. Pressing CTRL in the Main Menu displays some stuff at the top (Probably not a bug). EDIT: THIS IS INTENTIONAL. It shows player count and exp multiplier

- [x] 25. in Stats, UFO's model is just a white ball.

- [x] 26. in Stats, it says Asteroids at the top but displays UFOs and Motherships. EDIT: THIS IS INTENTIONAL, they are in the same group but I think I'll change it to "Enemies" to avoid confusion

- [x] 27. When hovering over a Weapon/Ability/Utility and switching category (Weapons, Abilities, or Utilities categories), the item is still displayed on the right but it's xp counter is reset to 0.

- [x] 28. I used Super Skip in Weekly Planet and had to wait after killing the enemies for the Sector to end, even though the bug was fixed everywhere else.

- [x] 29. Hovering over cleared Sectors still displays the Battle button but it doesn't react to being clicked on.

- [x] 30. Abilities seem to be capped at level 10.

**Comment by Infiland** [comment]
I updated this comment with checkboxes, the ones that are fixed or intentional are checked out
